spring:
  datasource:
    url: jdbc:postgresql://ec2-18-204-142-254.compute-1.amazonaws.com:5432/deaijgv144vrat
    username: xkxhsdqjbzgcpa
    password: f45bfcf83320bbcdc55e81304c2a9e07a3613c04857726d709144b2a87030d24
    hikari:
      schema: public
  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    schemas: public
    locations: classpath:db/migration

