
version: 2.1
workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
         requires:
         - build
      - deployToStage:
         requires:
         -build
         - test

#      - hold:
#          type: approval
#          requires:
#            - build
#            - test
#      - deployToProduction:
#          type: approval
#          requires:
#            - build
#            - test


jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: ./gradlew bootJar
      - persist_to_workspace:
          root: ./
          paths:
            - build/
            - .gradle/
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: ./gradlew test


      - store_test_results:
          path: build/test-results
      - store_artifacts:
#          path: build/reports

           path: build/jacoco
           destination : test_coverage


  deployToStage:
    docker:  #executor: type
        - image: circleci/openjdk:8-jdk
    steps:
        - checkout
        - setup_remote_docker:
            version: 20.10.14
        - attach_workspace:
            at: ./
#        - run: docker build -f Dockerfile . -t teama
        - run:
            name: Build and push Docker image to Heroku
            command: |
              set -x
              sudo curl https://cli-assets.heroku.com/install.sh | sh
              HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
              HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a bibliotecateama web
              HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a bibliotecateama web

#  deployToProduction:
#    docker: #executor: type
#      - image: circleci/openjdk:8-jdk
#    steps:
#      - checkout
#      - setup_remote_docker:
#          version: 20.10.14
#      - attach_workspace:
#          at: ./
#      #        - run: docker build -f Dockerfile . -t teama
#      - run:
#          name: Build and push Docker image to Heroku to production
#          command: |
#            set -x
#            sudo curl https://cli-assets.heroku.com/install.sh | sh
#            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
#            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a bibliotecateamaproduction web
#            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a bibliotecateamaproduction web

